### ISSUE TITLE
出现了下面的错误，要怎么处理

### ISSUE THREAD

**Issue by yxsongbo** [aoaoemoji/FiimeExcelTool#1]
当前工作目录:D:\2
请输入需要转换的格式, 选择序号:
1
当前进行到:D:\2\24104020020035_苗瑛琪.xlsx
当前进行到:D:\2\24104020020063_方舟.xlsx
当前进行到:D:\2\24104020020066_洪鸣霞.xlsx
Traceback (most recent call last):
  File "xls.py", line 289, in <module>
    makexls()
  File "xls.py", line 51, in makexls
    wb = excel.Workbooks.Open(filedir)
  File "C:\ProgramData\Anaconda3\lib\site-packages\win32com\gen_py\00020813-0000-0000-C000-000000000046x0x1x9\Workbooks.py", line 75, in Open
    ret = self._oleobj_.InvokeTypes(1923, LCID, 1, (13, 0), ((8, 1), (12, 17), (12, 17), (12, 17), (12, 17), (12, 17), (12, 17), (12, 17), (12, 17), (12, 17), (12, 17), (12, 17), (12, 17), (12, 17), (12, 17)),Filename
pywintypes.com_error: (-2147352567, '发生意外。', (0, 'Microsoft Excel', '类 Workbooks 的 Open 方法无效', 'xlmain11.chm', 0, -2146827284), None)

**Comment by aoaoemoji** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
